// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pack} from '../models';
import {main} from '../models';
import {catalogue} from '../models';

export function ApplyPack(arg1:pack.Pack):Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearPack():Promise<void>;

export function ClearRobloxCache():Promise<string>;

export function DeleteInstalledMgpack(arg1:string):Promise<void>;

export function DisableMegiddo():Promise<void>;

export function EnableMegiddo(arg1:pack.Pack):Promise<void>;

export function EnableMegiddoProfiles(arg1:Array<string>):Promise<void>;

export function ExportMgpack(arg1:pack.Pack):Promise<string>;

export function GetCatalogue():Promise<catalogue.Snapshot>;

export function GetLogs():Promise<Array<string>>;

export function GetProxyStatus():Promise<main.ProxyStatus>;

export function GetRobloxCertPatchStatus():Promise<main.CertPatchStatus>;

export function IsMegiddoEnabled():Promise<boolean>;

export function ListInstalledMgpacks():Promise<Array<main.InstalledPackInfo>>;

export function LoadInstalledMgpack(arg1:string):Promise<pack.Pack>;

export function LoadMgpackFromFile():Promise<pack.Pack>;

export function LoadPackFromURL(arg1:string):Promise<pack.Pack>;

export function MergeInstalledMgpacks(arg1:Array<string>):Promise<pack.Pack>;

export function PatchRobloxCerts():Promise<main.CertPatchStatus>;

export function PickLocalAssetFile(arg1:string):Promise<string>;

export function SaveInstalledMgpack(arg1:string,arg2:pack.Pack):Promise<void>;

export function UnpatchRobloxCerts():Promise<main.CertPatchStatus>;
