// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPack(arg1) {
  return window['go']['main']['App']['ApplyPack'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearPack() {
  return window['go']['main']['App']['ClearPack']();
}

export function ClearRobloxCache() {
  return window['go']['main']['App']['ClearRobloxCache']();
}

export function DeleteInstalledMgpack(arg1) {
  return window['go']['main']['App']['DeleteInstalledMgpack'](arg1);
}

export function DisableMegiddo() {
  return window['go']['main']['App']['DisableMegiddo']();
}

export function EnableMegiddo(arg1) {
  return window['go']['main']['App']['EnableMegiddo'](arg1);
}

export function EnableMegiddoProfiles(arg1) {
  return window['go']['main']['App']['EnableMegiddoProfiles'](arg1);
}

export function ExportMgpack(arg1) {
  return window['go']['main']['App']['ExportMgpack'](arg1);
}

export function GetCatalogue() {
  return window['go']['main']['App']['GetCatalogue']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetRobloxCertPatchStatus() {
  return window['go']['main']['App']['GetRobloxCertPatchStatus']();
}

export function IsMegiddoEnabled() {
  return window['go']['main']['App']['IsMegiddoEnabled']();
}

export function ListInstalledMgpacks() {
  return window['go']['main']['App']['ListInstalledMgpacks']();
}

export function LoadInstalledMgpack(arg1) {
  return window['go']['main']['App']['LoadInstalledMgpack'](arg1);
}

export function LoadMgpackFromFile() {
  return window['go']['main']['App']['LoadMgpackFromFile']();
}

export function LoadPackFromURL(arg1) {
  return window['go']['main']['App']['LoadPackFromURL'](arg1);
}

export function MergeInstalledMgpacks(arg1) {
  return window['go']['main']['App']['MergeInstalledMgpacks'](arg1);
}

export function PatchRobloxCerts() {
  return window['go']['main']['App']['PatchRobloxCerts']();
}

export function PickLocalAssetFile(arg1) {
  return window['go']['main']['App']['PickLocalAssetFile'](arg1);
}

export function SaveInstalledMgpack(arg1, arg2) {
  return window['go']['main']['App']['SaveInstalledMgpack'](arg1, arg2);
}

export function UnpatchRobloxCerts() {
  return window['go']['main']['App']['UnpatchRobloxCerts']();
}
